### ISSUE TITLE
feat: login using next-auth

### ISSUE THREAD

**Issue by RamGoel** [RamGoel/ticketo#1]
Integrate Google Login using next auth

**Comment by adityaK87** [comment]
I want to work on this issue, can you assign this to me?

**Comment by RamGoel** [comment]
Thanks for contributing @adityaK87 🚀

**Comment by RamGoel** [comment]
@adityaK87 any update?

**Comment by 17rawat** [comment]
hey ram, can I continue on this?

**Comment by RamGoel** [comment]
sure go ahead @17rawat !

**Comment by 17rawat** [comment]
Hey ram, its done. check my PR.

**Comment by adityaK87** [comment]
hey ram working on it
