### ISSUE TITLE
feat: responsive for mobile devices

### ISSUE THREAD

**Issue by RamGoel** [RamGoel/ticketo#2]
The task is to make the whole web app responsive for mobile devices, the entire UI is built with nextjs and plain CSS.

**Comment by adityaK87** [comment]
Hey!! I would like to contribute to this issue. Can u assign me this??

**Comment by RamGoel** [comment]
@adityaK87 , I have assigned you #1 . 
Let's take one issue at a time. 
Will be more than happy to assign you once you submit a PR for #1.

**Comment by divyansh956** [comment]
![image](https://github.com/RamGoel/ticketo/assets/96046430/7a6df959-a856-4a76-97d1-0a88ecc52a4a)
I am getting a module error while running on vs code, I have installed all the necessary modules but still could not fix
- **npm i iconsax-react**

**Comment by RamGoel** [comment]
> ![image](https://user-images.githubusercontent.com/96046430/272000846-7a6df959-a856-4a76-97d1-0a88ecc52a4a.png) I am getting a module error while running on vs code, I have installed all the necessary modules but still could not fix
> 
> * **npm i iconsax-react**

Try deleting the node_modules folder once and reinstall all dependencies by `npm i --force`

**Comment by divyansh956** [comment]
It worked, I would like to make it mobile responsive through tailwind css

**Comment by RamGoel** [comment]
Yes sure, go ahead

**Comment by divyansh956** [comment]
![image](https://github.com/RamGoel/ticketo/assets/96046430/d0032be0-58dd-4c68-9c1d-f96c3258d5f1)
After the latest pull i am getting this error, do i need to make the env first and connect it with google?

**Comment by RamGoel** [comment]
@divyansh956 Take a pull, it should work now
