### ISSUE TITLE
Add a Contributing.md

### ISSUE THREAD

**Issue by RamGoel** [RamGoel/ticketo#3]
Can someone help with a Contributing.md file so that it will be easy for coming contributors to understand about the do's and don't while contributing.

A Checklist of items need to be in file :

- [ ] Proper naming convention for commits
- [ ] Proper naming convention for PR's
- [ ] About project
- [ ] How to report a issue
- [ ] Step by Step process of Contributing (fork, branch, etc)

If you have any ideas, feel free to discuss, we'll add them to list.

Thanks

**Comment by Madhura-saw** [comment]
Hi @RamGoel can I work on this?

**Comment by RamGoel** [comment]
@Madhura-saw Sure, go ahead 🚀

**Comment by MeetD99** [comment]
I would like to work on this Issue, can you assign me this issue as well?

**Comment by RamGoel** [comment]
@Madhura-saw , any update on this?

**Comment by Madhura-saw** [comment]
Still working, will send a PR by EOD today

**Comment by RamGoel** [comment]
@MeetD99 , Madhura-saw already has some progress on it. I suggest you to go and check out the website and find some issues/improvements and report them and assign them to yourself.
